services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgres-data:

networks:
  postgres:
    driver: bridge
